Repository woocommerce/woocommerce-gateway-payfast, pull requests merged in 2023-11, with the labels that each got.

#171 Fix e2e tests: Update default behavior to use a block-based cart and checkout
  tests/e2e/bin/initialize.sh
  tests/e2e/config/checkout-block-page.txt
  tests/e2e/specs/admin/edit-settings.test.js
  tests/e2e/specs/payment-flow/cancelled-one-time-payment.test.js
  tests/e2e/specs/payment-flow/one-time-payment.test.js
  tests/e2e/specs/payment-flow/subscription-payment.test.js
  tests/e2e/utils/index.js
Labels: status: e2e tests passing

#172 Bump WooCommerce "tested up to" 8.3
  gateway-payfast.php
Labels: status: e2e tests passing, status: e2e tests failing

#173 Create `dependabot.yml`
  .github/dependabot.yml
Labels: changelog: none

#170 Compatibility testing with WordPress 6.4
  README.md
  gateway-payfast.php
  readme.txt
Labels: status: e2e tests passing

#160 upkeep/156 Standardize PHPCS and PHPCompatibility GH Actions
  .gitattributes
  .github/workflows/main.yml
  .github/workflows/php-compat.yml
  .github/workflows/php-compatibility.yml
  .github/workflows/phpcs.yml
  composer.json
  composer.lock
  package.json
  phpcs-compat.xml.dist
  phpcs.xml.dist
Labels: needs: Regression

#175 Release/1.6.0
  changelog.txt
  gateway-payfast.php
  package-lock.json
  package.json
  readme.txt
Labels: needs: qit default tests, status: e2e tests passing
