Repository woocommerce/woocommerce-gateway-payfast, pull requests merged in 2024-11, with the labels that each got.

#264 Release/1.6.8
  changelog.txt
  package-lock.json
  package.json
  readme.txt
  woocommerce-gateway-payfast.php
Labels: needs: qit default tests, status: e2e tests passing

#265 Compatibility testing with WordPress 6.7
  readme.txt
  woocommerce-gateway-payfast.php
Labels: status: e2e tests passing, needs: WP RC test

#268 Release/1.6.9
  changelog.txt
  package-lock.json
  package.json
  readme.txt
  woocommerce-gateway-payfast.php
Labels: needs: qit default tests, status: e2e tests passing

#269 Bump WooCommerce "tested up to" version 9.5
  woocommerce-gateway-payfast.php
Labels: status: e2e tests passing
