Repository woocommerce/woocommerce-gateway-payfast, pull requests merged in 2024-07, with the labels that each got.

#239 Bump WordPress Tested up to version 6.6
  README.md
  readme.txt
  woocommerce-gateway-payfast.php
Labels: needs: qit e2e test, status: e2e tests passing, needs: WP RC test

#242 Compatibility testing with Woo 9.1
  woocommerce-gateway-payfast.php
Labels: status: e2e tests passing

#228 upkeep/222: modernize developer experience
  .github/workflows/e2e.yml
  .nvmrc
  README.md
  includes/class-wc-gateway-payfast-blocks-support.php
  package-lock.json
  package.json
  src/blocks/payment-method/constants.js
  src/blocks/payment-method/index.js
  src/blocks/payment-method/payfast-utils.js
  tests/e2e/playwright.config.js
  webpack.config.js
Labels: status: e2e tests passing

#244 Release/1.6.6
  changelog.txt
  includes/class-wc-gateway-payfast.php
  package-lock.json
  package.json
  readme.txt
  woocommerce-gateway-payfast.php
Labels: needs: qit default tests, status: e2e tests passing
