Repository woocommerce/woocommerce-gateway-payfast, pull requests merged in 2024-05, with the labels that each got.

#215 Compatibility testing with Woo 8.8
  woocommerce-gateway-payfast.php
Labels: status: e2e tests passing

#219 Decode HTML entity encoding in the site name before sending data to Payfast.
  includes/class-wc-gateway-payfast.php
Labels: status: e2e tests passing

#221 Release/1.6.4
  changelog.txt
  package-lock.json
  package.json
  readme.txt
  woocommerce-gateway-payfast.php
Labels: needs: qit default tests, status: e2e tests passing

#227 Release/1.6.5
  changelog.txt
  package-lock.json
  package.json
  readme.txt
  woocommerce-gateway-payfast.php
Labels: needs: qit default tests
